platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: "8"

inputs:
- name: MUMWebStore-git

run:
  path: echo
  args: [MUMWebStore-git/ci/tasks]
  path: ./MUMWebStore-git/ci/tasks/package.bat